name: Deploy to EC2

on:
  push:
    branches: [ main ]  # Change to your primary branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          EC2_HOST: 3.127.58.246
          EC2_USER: ec2-user
        run: |
          # Ensure SSH host key is recognized
          mkdir -p ~/.ssh
          ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
          
          # Copy application files to EC2
          rsync -avz ./ishe-server/ $EC2_USER@$EC2_HOST:~/ishe-server/
          
          # Execute commands individually to avoid heredoc issues
          ssh $EC2_USER@$EC2_HOST "cd ~/ishe-server && sudo docker-compose down"
          ssh $EC2_USER@$EC2_HOST "cd ~/ishe-server && sudo docker-compose build"
          ssh $EC2_USER@$EC2_HOST "cd ~/ishe-server && sudo docker-compose up -d"
          ssh $EC2_USER@$EC2_HOST "cd ~/ishe-server && sudo docker system prune -f" 